### ISSUE TITLE
Information on sensory friendliness is missing

### ISSUE THREAD

**Issue by katsel** [numfocus/DISCOVER-Cookbook#14]
The cookbook lacks any information on **sensory friendliness**, which is a requirement for people with various mental health issues and chronic illnesses (e.g., people with asthma or migraines), disabled people (e.g., autistics), and people with sensory processing disorder.

**Comment by Dr-G** [comment]
Thank you for pointing this out, @katsel! Are there particular resources on sensory friendliness you'd recommend we reference?

**Comment by katsel** [comment]
I am [keeping a list](https://gist.github.com/katsel/b8fbd1a35734708d5e654bb5153a5aa3) of resources I've encountered so far and found useful with conference organisation. Just updated with a few links on neurodiversity friendliness (which includes sensory things).
Feel free to use with attribution.

**Comment by Dr-G** [comment]
https://github.com/numfocus/DISCOVER-Cookbook/blob/master/venue-selection.md

Thanks, @katsel!

**Comment by tkoyama010** [comment]
@all-contributors please add @katsel for ideas
