### ISSUE TITLE
Pronoun Ribbons

### ISSUE THREAD

**Issue by oxinabox** [numfocus/DISCOVER-Cookbook#17]
Another option for pronoun indication is ribbons.
At some conventions and conferences badge ribbons are popular.
http://www.pronounribbons.org/

I've used the ones from the Pronoun Ribbon Project ( page seems dead: https://sites.google.com/site/pronounribbons/) before.
As well as having custom ones printed for Zi/Zir,  and a "Fill in your own" ribbon,
For fill in your own, one requires a fabric marker,
and it doesn't work as well as the preprinted ones

**Comment by Dr-G** [comment]
Thanks @oxinabox! 
https://github.com/numfocus/DISCOVER-Cookbook/blob/master/inclusive_practices_during_checkin.md

**Comment by tkoyama010** [comment]
@all-contributors please add @oxinabox for ideas
