### ISSUE TITLE
Turn this into a website

### ISSUE THREAD

**Issue by choldgraf** [numfocus/DISCOVER-Cookbook#19]
There's a lot of useful material in here! Perhaps it could be more discoverable / have a higher impact if it was in website form instead of as a github repo. Since everything is in Markdown already, it should be pretty easy to build it into documentation with Mkdocs (https://www.mkdocs.org/). Should just be a matter of adding the config file and hosting with Readthedocs. Just a thought!

**Comment by munkm** [comment]
Hey Chris, thank you for bringing this up. This is a great suggestion! We have a group of volunteers who have been doing work putting all of this information in a Jekyll page, here: https://discover-cookbook.github.io . They're still working on it, but it will be ready soon. We'd love any feedback you'd be interested in giving on it! 

I think this issue should remain open until the webpage is finished.

**Comment by aterrel** [comment]
Great to hear! If ya'll need a custom domain or subdomain of numfocus.org,
let me know. I can set that up for you.

-- Andy

**Comment by choldgraf** [comment]
very cool! I'll close this, since it sounds like this idea is already on your radar :-)

**Comment by tkoyama010** [comment]
@all-contributors please add @choldgraf for ideas
