### ISSUE TITLE
More guidance on hearing impaired

### ISSUE THREAD

**Issue by oxinabox** [numfocus/DISCOVER-Cookbook#25]
This section https://github.com/numfocus/DISCOVER-Cookbook/blob/master/04_venue_selection.md#disability

> -  ✅ Book sign-language interpreters and/or real-time captioning (someone typing captions) for deaf and hard-of-hearing attendees.

It would be useful to include a bit more information, as to which is preferable under what circumstances between sign-language interpreters vs real-time captioning, assuming the budget does not allow for both.
I have read a little about Sign-language being generally preferred by those born deaf, and captions by those who aquire hearing loss later in life.
And that in general captioning is more useful 
https://therebuttal2.com/2016/01/28/captioning-vs-sign-language-a-no-brainer/

>    - Make sure that hand-held microphones are available

Should this be extended to say something about having the session chairs ensure that the microphone is used, even if the speaker thinks there voice is loud enough?
Not just available, but used.
See e.g.
https://www.chronicle.com/article/A-Note-From-Your-Colleagues/245916

--- 

Also is there something that should be added about hooking in to a venue's **hearing loop** (aka induction loop, aka T-loop).
And about choising venues that provier this?

**Comment by Dr-G** [comment]
we have included these suggestions in #32 — thank you!
