### ISSUE TITLE
add link to feedback survey

### ISSUE THREAD

**Issue by Dr-G** [numfocus/DISCOVER-Cookbook#35]
add a link to the cookbook feedback survey to the cookbook!
https://numfocus.typeform.com/to/rVWlSW

**Comment by chet400** [comment]
I have Added the link in index.md of cookbook
let me know if any more change need

**Comment by aterrel** [comment]
Is there someone watching the typeform answers? I don't think adding this if it isn't maintained is a good idea.

**Comment by mikofski** [comment]
>Is there someone watching the typeform

honestly I doubt it but maybe ask @arliss-NF ?

**Comment by aterrel** [comment]
okay closing as not needed. If @arliss-NF or anyone at @numfocus/disc-steering-committee is disagrees, please reopen ticket and provide needed policy and privacy guidance for a continuously running survey.
