### ISSUE TITLE
Switch to jupyterbook

### ISSUE THREAD

**Issue by terezaif** [numfocus/DISCOVER-Cookbook#47]
We've worked at swithcing to using jupyterbook and redesign it a bit and adding new post covid stuff

**Comment by mikofski** [comment]
can check out a preview version here: https://numfocus.github.io/DISCOVER-handbook/

**Comment by tkoyama010** [comment]
@all-contributors please ad @terezaif for ideas

**Comment by tkoyama010** [comment]
@all-contributors please add @terezaif for ideas

**Comment by tkoyama010** [comment]
@all-contributors please add @noatamir for maintenance
