### ISSUE TITLE
rethink tags

### ISSUE THREAD

**Issue by noatamir** [numfocus/DISCOVER-Cookbook#49]
documents have tags hardcoded in content with HTML to color them red, but no crossref links

EG: https://github.com/numfocus/DISCOVER-handbook/blob/jupyter-init/DISCOVER/06_childcare.md

```markdown
---
layout: page
title: Childcare
---

# Childcare

**Tags:** <span style="color:red">Parents and Carers</span>, <span style="color:red">Participant Diversity</span>, <span style="color:red">Scholarships</span>

✅ Offer financial support for childcare.
 - Build it into your budget. 
   - Link it to sponsorships, or university partners, or ...
```

There's a section in jupyter book docs to create cross references here:
* https://jupyterbook.org/en/stable/content/references.html
* https://jupyterbook.org/en/stable/tutorials/references.html

Need to do more research to see if this is useful for tags. Turns out jbook is built on top of Sphinx, so there are similarities.

here is a tool to create tags in jupyterbooks/sphinx: https://github.com/melissawm/sphinx-tags

**Comment by mikofski** [comment]
copied from temporary transition repo "discover-handbook"
https://github.com/numfocus/DISCOVER-handbook/issues/5

**Comment by noatamir** [comment]
replaces and closes #39

**Comment by mikofski** [comment]
As discussed on 2023-02-06, we will remove all tags for now.

**Comment by mikofski** [comment]
stumbled across this from @melissawm : https://github.com/melissawm/sphinx-tags maybe we can use it?
