### ISSUE TITLE
remove glossary

### ISSUE THREAD

**Issue by mikofski** [numfocus/DISCOVER-Cookbook#61]
There's now a glossary page that was repurposed from taxonomy which was itself replaced by the tags overview generated content.

As discussed in [JBook special roles, we can add glossary terms to content](https://jupyterbook.org/en/stable/content/content-blocks.html#glossaries).
![image](https://user-images.githubusercontent.com/1385621/217791372-6c43f353-77f9-46a3-8d5e-adf55155ae16.png)

- [ ] link to terms where they are used like <code>{term}`A second term`</code>
- [ ] add terms to glossary page (old taxonomy page)

**Comment by tkoyama010** [comment]
@all-contributors please add @mikofski for ideas
