### ISSUE TITLE
Python 3.7 not supported by CI upgrade to Python 3.9

### ISSUE THREAD

**Issue by mikofski** [numfocus/DISCOVER-Cookbook#76]
See https://github.com/numfocus/DISCOVER-Cookbook/pull/65/checks#step:3:6

**Comment by aterrel** [comment]
I suggest upgrading to 3.13 so it doesn't fail again in 6 months

**Comment by aterrel** [comment]
Okay looks like Python 3.13 isn't supported by Github yet, so used 3.12.8.

The workflows seems to be failing though for separate reasons:
preview: needs permission to deploy (see [error log](https://github.com/numfocus/DISCOVER-Cookbook/actions/runs/12493942396/job/34863078661))
checklinks: is inconsistent in finding errors (see [error log](https://github.com/numfocus/DISCOVER-Cookbook/actions/runs/12493942397/job/34863003638))

I propose we go ahead and accept #78, with the workflows switched to manual and create separate tickets for each workflow.

**Comment by mikofski** [comment]
>needs permission to deploy

Is this only for [rossjrw/pr-preview-action@v1](https://github.com/marketplace/actions/deploy-pr-preview)? It used to work when we set it up. I don’t if relevant but the [docs](https://github.com/marketplace/actions/deploy-pr-preview#grant-actions-permission-to-read-and-write-to-the-repository) say:
>grant actions permission to read and write to the repository…

This GitHub action just renders the Jupyter book from a PR to view it without having to build it locally offline. Convenient, but not 100% necessary.

**Comment by mikofski** [comment]
>I propose we go ahead and accept https://github.com/numfocus/DISCOVER-Cookbook/pull/78, with the workflows switched to manual and create separate tickets for each workflow.

Works for me

**Comment by aterrel** [comment]
Merged #78 and created tickets for failing workflows.
